### PR TITLE
partial c++20 module support

### LINKED ISSUE #2216: sccache doesn't support c++module well
in a c++20 project with clang-18 and cmake 3.28.3 in ubuntu 24.04，if c++module is used， sccache doen't cache the correct compilation result. it seems that it can't distingguish the same .cpp file importing modifed different version of c++module and will reused the wrong cached file, thus resulting SIGSEGV while executing the generated executable.   disabling sccache, problem is gone.

### PR DESCRIPTION
**Pull request by TroyKomodo**
Adds partial support for c++20 modules when using clang.

Also detects when modules are used in MSVC / GCC and disable cache for those calls.

fixes #2216

partially addresses #2095

the clang c++20 module implementation (as well as msvc) is rather easy to parse and understand so adding support for it is fairly trivial. GCC however is a mess. An entirely different approach will be needed to get GCC module support which is far out side of the scope for this initial PR. 

I will submit future PRs to get MSVC / GCC.

Test with nix

```nix
(pkgs.sccache.overrideAttrs (final: old: {
  version = "troy/cxx20-modules";
  cargoHash = "sha256-tCQrZ6cPGJrxHgeSJ4ZqZs6otWvVu6Ys3svAiwvmSDc=";
  src = fetchFromGitHub {
    owner = "troykomodo";
    repo = "sccache";
    rev = "troy/cxx20-modules";
    sha256 = "sha256-A0n/nsNPTHRC0Z6ERwCpoR1w3O/xl6d1yCw/5GeqNd4=";
  };
  cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
    inherit (final) pname src version;
    hash = final.cargoHash;
  };
}))
```

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
FYI https://github.com/ccache/ccache/pull/1523

**Comment by TroyKomodo** [comment]
> The code looks good to me. I'll probably try to test it some time next week.
> 
> I can help out with GCC module map file parsing too (it will need to actually be parsed due to the `$root` meta-descriptor). However, the output path is also given by it…that may prove more difficult to "know".

Thanks! It was my first time contributing to sccache so I'm not too familiar with the process. 

I will fix up the clippy issues + windows test issues :p

**Comment by mathstuf** [comment]
It looks like BMI-only compilations are not properly considered:

```
467:    actual-stdout> [2-1->6/8@76.9] Building CXX object 'CMakeFiles/CXXModules__export_from_ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi'          
467:    actual-stdout> FAILED: [code=254] CMakeFiles/CXXModules__export_from_ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi 
467:    actual-stdout> /home/boeckb/code/depot/group-devel/sccache/src/target/debug/sccache  /usr/lib64/ccache/clang++   -g -std=gnu++20 --precompile -MD -MT 'CMakeFiles/CXXModules__
export_from_ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi' -MF CMakeFiles/CXXModules__export_from_ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi.d @CMakeFiles/CXXModules__export_from_
ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi.modmap -o 'CMakeFiles/CXXModules__export_from_ninja@synth_cf4e03cd8b1e.dir/35a7889ff75f.bmi' -c /home/boeckb/misc/builds/cmake/build-cla
ng/Tests/RunCMake/CXXModulesCompile/exp-mods-from-ninja-ninja-install/lib/cxx/miu/importable.cxx
467:    actual-stdout> sccache: encountered fatal error
467:    actual-stdout> sccache: error: Failed to generate compile commands
467:    actual-stdout> sccache: caused by: Failed to generate compile commands
467:    actual-stdout> sccache: caused by: Missing object file output
```

This is from running CMake's `CXXModules` tests:

```sh
export SCCACHE_SERVER_PORT=23448 # unique to avoid ambient re-usage
export CXX="$(which sccache) $(which clang++)"
ctest -R CXXModules
```

**Comment by mathstuf** [comment]
You can ignore the tests failing about JSON argument list mismatches; it is not robust against mutli-argument compilers like here. If you do the "symlink trick" (`ln -s $(which sccache) clang++ && export CXX="$PWD/clang++"`, that probably avoids the issue).

**Comment by TroyKomodo** [comment]
Hmm, i think this is just me forgetting to change it somewhere. I will fix

**Comment by TroyKomodo** [comment]
Okay so it seems i think we should always treat it as an object even if it really isnt...

**Comment by TroyKomodo** [comment]
I think it works...

I tried the cmake tests and they ran fine for me but there were only 2...

```
roy@troy-thinkpad ~/g/t/C/build (master) [SIGINT]> ctest -R CXXModules -j$(nproc)                                                                                   nix-shell 
Test project /home/troy/github/troy/CMake/build
Guessing configuration NoConfig
    Start 537: RunCMake.CXXModules
    Start 538: RunCMake.CXXModulesCompile
1/2 Test #538: RunCMake.CXXModulesCompile .......   Passed    0.53 sec
2/2 Test #537: RunCMake.CXXModules ..............   Passed   23.35 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
CXXModules    =  23.88 sec*proc (2 tests)

Total Test time (real) =  23.36 sec
```

**Comment by sylvestre** [comment]
could you please add an integration test ? ie high level which integrates into cmake and uses C++ module.
see
tests/cmake/ tests/sccache_args.rs  tests/sccache_cargo.rs  tests/sccache_rustc.rs

**Comment by mathstuf** [comment]
> I tried the cmake tests and they ran fine for me but there were only 2...

There are dozens of test cases within each CTest-level test. These are the relevant ones, thanks!

Can you inspect the cache state (`--show-stats`) on an initial run and a subsequent run to see how well caching itself is working?

**Comment by TroyKomodo** [comment]
> could you please add an integration test ? ie high level which integrates into cmake and uses C++ module.
> 
> see
> 
> tests/cmake/ tests/sccache_args.rs  tests/sccache_cargo.rs  tests/sccache_rustc.rs
> 
> 

Yes!

**Comment by TroyKomodo** [comment]
> > I tried the cmake tests and they ran fine for me but there were only 2...
> 
> There are dozens of test cases within each CTest-level test. These are the relevant ones, thanks!
> 
> Can you inspect the cache state (`--show-stats`) on an initial run and a subsequent run to see how well caching itself is working?

```
troy@troy-thinkpad ~/g/t/C/build (master)> ctest -R CXXModules -j$(nproc)                                                                                            nix-shell 
Test project /home/troy/github/troy/CMake/build
Guessing configuration NoConfig
    Start 537: RunCMake.CXXModules
    Start 538: RunCMake.CXXModulesCompile
1/2 Test #538: RunCMake.CXXModulesCompile .......   Passed    0.66 sec
2/2 Test #537: RunCMake.CXXModules ..............   Passed   22.32 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
CXXModules    =  22.98 sec*proc (2 tests)

Total Test time (real) =  22.33 sec
troy@troy-thinkpad ~/g/t/C/build (master)> sccache -s                                                                                                                nix-shell 
Compile requests                    192
Compile requests executed            39
Cache hits                           35
Cache hits (C/C++)                   35
Cache misses                          4
Cache misses (C/C++)                  4
Cache hits rate                   89.74 %
Cache hits rate (C/C++)           89.74 %
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Cache errors                          0
Compilations                          4
Compilation failures                  0
Non-cacheable compilations            0
Non-cacheable calls                  38
Non-compilation calls               115
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  0.041 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
-E                                   38

Cache location                  Local disk: "/home/troy/.cache/sccache"
Use direct/preprocessor mode?   yes
Version (client)                0.12.0
Cache size                            6 KiB
Max cache size                       10 GiB
troy@troy-thinkpad ~/g/t/C/build (master)> ctest -R CXXModules -j$(nproc)                                                                                            nix-shell 
Test project /home/troy/github/troy/CMake/build
Guessing configuration NoConfig
    Start 537: RunCMake.CXXModules
    Start 538: RunCMake.CXXModulesCompile
1/2 Test #538: RunCMake.CXXModulesCompile .......   Passed    0.53 sec
2/2 Test #537: RunCMake.CXXModules ..............   Passed   22.58 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
CXXModules    =  23.11 sec*proc (2 tests)

Total Test time (real) =  22.60 sec
troy@troy-thinkpad ~/g/t/C/build (master)> sccache -s                                                                                                                nix-shell 
Compile requests                    384
Compile requests executed            78
Cache hits                           74
Cache hits (C/C++)                   74
Cache misses                          4
Cache misses (C/C++)                  4
Cache hits rate                   94.87 %
Cache hits rate (C/C++)           94.87 %
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Cache errors                          0
Compilations                          4
Compilation failures                  0
Non-cacheable compilations            0
Non-cacheable calls                  76
Non-compilation calls               230
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  0.041 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
-E                                   76

Cache location                  Local disk: "/home/troy/.cache/sccache"
Use direct/preprocessor mode?   yes
Version (client)                0.12.0
Cache size                            6 KiB
Max cache size                       10 GiB
troy@troy-thinkpad ~/g/t/C/build (master)>    
```

Cache didnt really improve time here but on my repo it does a lot...

```
[298/299] Linking CXX executable examples/Debug/basic_example

________________________________________________________
Executed in   32.70 secs    fish           external
   usr time    4.13 secs    0.54 millis    4.13 secs
   sys time    3.45 secs    2.31 millis    3.45 secs
   
  ---
  
  [298/299] Linking CXX executable examples/Debug/basic_example

________________________________________________________
Executed in    7.66 secs    fish           external
   usr time    4.23 secs    1.85 millis    4.23 secs
   sys time    3.38 secs    1.51 millis    3.38 secs
```

```

troy@troy-thinkpad ~/g/p/v10-sdk-working (main)> sccache -s                                                                                                                paravision-shell-env 
Compile requests                    416
Compile requests executed           412
Cache hits                          200
Cache hits (C/C++)                  200
Cache misses                        210
Cache misses (C/C++)                210
Cache hits rate                   48.78 %
Cache hits rate (C/C++)           48.78 %
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Cache errors                          2
Cache errors (C/C++)                  2
Compilations                        210
Compilation failures                  0
Non-cacheable compilations            0
Non-cacheable calls                   4
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.001 s
Average compiler                  0.572 s
Average cache read hit            0.001 s
Failed distributed compilations       0

Non-cacheable reasons:
multiple input files                  4

Cache location                  Local disk: "/home/troy/.cache/sccache"
Use direct/preprocessor mode?   yes
Version (client)                0.12.0
Cache size                          126 MiB
Max cache size                       10 GiB
troy@troy-thinkpad ~/g/p/v10-sdk-working (main)>    
```

~50% cache hit because i ran it the first time (no cache hits), then reran it so 100% cache hit.

**Comment by TroyKomodo** [comment]
https://github.com/mozilla/sccache/actions/runs/20413181927/job/58653103431 test results look good!

**Comment by sylvestre** [comment]
are you sure ?
```
Run ${SCCACHE_PATH} --show-stats
Compile requests                      4
Compile requests executed             4
Cache hits                            2
Cache hits (C/C++)                    2
Cache misses                          2
Cache misses (C/C++)                  2
Cache hits rate                   50.00 %
Cache hits rate (C/C++)           50.00 %

```

**Comment by TroyKomodo** [comment]
That seems right no? the first time we invoke the compiler not cached yet then we invoke again and its cached.

There are only 2 files to compile, so i expected it to be 4 requests 2 hit 2 misses.

**Comment by sylvestre** [comment]
oh yeah, my bad, i thought we were doing a reset

**Comment by TroyKomodo** [comment]
> oh yeah, my bad, i thought we were doing a reset

I just copied the other cmake test example, but I can reset the stats if that makes it easier to follow

**Comment by mathstuf** [comment]
Gah, module compilation in the tests doesn't really *happen* without a setting. For `clang`, this should work:

`-DCMake_TEST_MODULE_COMPILATION=named,compile_commands,collation,partitions,internal_partitions,export_bmi,install_bmi,shared,bmionly,build_database,import_std23`

File: src/compiler/gcc.rs [hunk 1]
```diff
@@ -371,6 +384,15 @@ where
                 };
             }
             Some(Output(p)) => output_arg = Some(p.clone()),
+            Some(ClangModuleOutput(p)) => {
+                if let Some(p) = p.split_prefix("=") {
+                    module_output_path = Some(Some(PathBuf::from(p)));
+                } else if p.is_empty() {
+                    module_output_path = Some(None);
+                } else {
+                    cannot_cache!("unknown module output format");
```
Comment (sylvestre) [inline src/compiler/gcc.rs]: maybe output the string in the error message too to help with debugging

File: src/compiler/gcc.rs [hunk 2]
```diff
@@ -664,6 +714,34 @@ where
         );
     }
 
+    if !module_only_flag {
+        if let Some(module_output_path) = module_output_path {
```
Comment (sylvestre) [inline src/compiler/gcc.rs]: could you please move this into a function?

File: tests/cmake-modules/CMakeLists.txt [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+set(CMAKE_CXX_STANDARD 20)
+set(CMAKE_CXX_STANDARD_REQUIRED ON)
+set(CMAKE_CXX_EXTENSIONS OFF)
+set(CMAKE_CXX_SCAN_FOR_MODULES ON)
+
+add_library(mymodule OBJECT)
+target_sources(mymodule PUBLIC FILE_SET CXX_MODULES FILES mymodule.cppm)
+
+add_library(myproject OBJECT main.cpp)
+target_link_libraries(myproject PRIVATE mymodule)
```
Comment (sylvestre) [inline tests/cmake-modules/CMakeLists.txt]:
```suggestion
target_link_libraries(myproject PRIVATE mymodule)

```

File: tests/cmake-modules/mymodule.cppm [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+
+export module mymodule;
+
+export void print_hello_world() {
+    std::cout << "Hello, World!" << std::endl;
+}
+
+export int add(int a, int b) {
+    return a + b;
+}
```
Comment (sylvestre) [inline tests/cmake-modules/mymodule.cppm]:
```suggestion
}

```

File: src/compiler/gcc.rs (hunk 2 above)
Comment (TroyKomodo) [reply src/compiler/gcc.rs]: I can, however this function is ~550 lines, I think it would be better if in a followup PR we break up this function rather than doing a half job here by breaking up just this one conditional.

**Comment by TroyKomodo** [comment]
> Gah, module compilation in the tests doesn't really _happen_ without a setting. For `clang`, this should work:
> 
> `-DCMake_TEST_MODULE_COMPILATION=named,compile_commands,collation,partitions,internal_partitions,export_bmi,install_bmi,shared,bmionly,build_database,import_std23`

Ah, I see. Okay I will try again i think i need to setup my env to have support for import std.

**Comment by TroyKomodo** [comment]
> > Gah, module compilation in the tests doesn't really _happen_ without a setting. For `clang`, this should work:
> > `-DCMake_TEST_MODULE_COMPILATION=named,compile_commands,collation,partitions,internal_partitions,export_bmi,install_bmi,shared,bmionly,build_database,import_std23`
> 
> Ah, I see. Okay I will try again i think i need to setup my env to have support for import std.

```nix
let
  pkgs = import <nixpkgs> {
    overlays = [
      (final: prev: {
        llvmPackages_21 = prev.llvmPackages_21 // {
          libcxx = prev.llvmPackages_21.libcxx.overrideAttrs (old: {
            postInstall = (old.postInstall or "") + ''
              substituteInPlace $out/lib/libc++.modules.json \
                --replace-fail '"../share' "\"$out/share"
            '';
          });
        };
      })
    ];
  };

  llvm = pkgs.llvmPackages_21;

  wrappedClangScanDeps = pkgs.writeShellScriptBin "clang-scan-deps" ''
    newargs=()
    inject_next=false
    for arg in "$@"; do
      if $inject_next; then
        newargs+=("$arg")
        newargs+=("-isystem" "${llvm.libcxx.dev}/include/c++/v1")
        inject_next=false
      elif [[ "$arg" == "--" ]]; then
        newargs+=("$arg")
        inject_next=true
      else
        newargs+=("$arg")
      fi
    done
    exec ${llvm.clang-tools}/bin/clang-scan-deps "''${newargs[@]}"
  '';

  sccache = "/home/troy/github/troy/sccache/result/bin/sccache";

  clangWrapper = pkgs.writeShellScriptBin "clang" ''
    exec ${sccache} "${llvm.libcxxClang}/bin/clang" "''${@}"
  '';
  clangxxWrapper = pkgs.writeShellScriptBin "clang++" ''
    exec ${sccache} "${llvm.libcxxClang}/bin/clang++" "''${@}"
  '';
in
pkgs.mkShell {
  hardeningDisable = [ "all" ];

  buildInputs = [
    pkgs.cmake
    pkgs.mold
    pkgs.ninja
    pkgs.openssl
    llvm.libcxxClang
    llvm.clang-tools
    wrappedClangScanDeps
  ];

  shellHook = ''
    export CC="${clangWrapper}/bin/clang"
    export CXX="${clangxxWrapper}/bin/clang++"
    export LD_LIBRARY_PATH="${llvm.libcxx.out}/lib:${pkgs.openssl.out}/lib:''${LD_LIBRARY_PATH:-}"
    export NIX_CFLAGS_COMPILE="-B${llvm.libcxx.out}/lib -isystem ${llvm.libcxx.dev}/include/c++/v1"
    export PATH="${wrappedClangScanDeps}/bin:''${PATH:-}"
  '';
}
```

A huge pain...

```
troy@troy-thinkpad ~/g/t/CMake (master) [SIGINT]> ctest -R CXXModules -j$(nproc) --test-dir=build   nix-shell 
Test project /home/troy/github/troy/CMake/build
Guessing configuration NoConfig
    Start 536: RunCMake.CXXModulesCompile
    Start 535: RunCMake.CXXModules
1/2 Test #535: RunCMake.CXXModules ..............   Passed   18.90 sec
2/2 Test #536: RunCMake.CXXModulesCompile .......   Passed  116.80 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
CXXModules    = 135.70 sec*proc (2 tests)

Total Test time (real) = 116.81 sec
troy@troy-thinkpad ~/g/t/CMake (master)> ctest -R CXXModules -j$(nproc) --test-dir=build            nix-shell 
Test project /home/troy/github/troy/CMake/build
Guessing configuration NoConfig
    Start 536: RunCMake.CXXModulesCompile
    Start 535: RunCMake.CXXModules
1/2 Test #535: RunCMake.CXXModules ..............   Passed   19.94 sec
2/2 Test #536: RunCMake.CXXModulesCompile .......   Passed  104.62 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
CXXModules    = 124.55 sec*proc (2 tests)

Total Test time (real) = 104.63 sec
troy@troy-thinkpad ~/g/t/CMake (master)>                                                            nix-shell 
```


```
Every 2.0s: /home/troy/github/troy/sccache/result/bin/sccache -s       troy-thinkpad: Mon Dec 22 12:47:11 2025

Compile requests                   1976
Compile requests executed           830
Cache hits                          756
Cache hits (C/C++)                  756
Cache misses                         72
Cache misses (C/C++)                 72
Cache hits rate                   91.30 %
Cache hits rate (C/C++)           91.30 %
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Cache errors                          0
Compilations                         72
Compilation failures                  2
Non-cacheable compilations            0
Non-cacheable calls                 244
Non-compilation calls               902
Unsupported compiler calls            0
Average cache write               0.001 s
Average compiler                  0.217 s
Average cache read hit            0.000 s
Failed distributed compilations       0

Non-cacheable reasons:
-E                                  244

Cache location                  Local disk: "/home/troy/github/troy/CMake/build/Tests/CMakeFiles/TestHome/.cac
he/sccache"
Use direct/preprocessor mode?   yes
Version (client)                0.12.0
Cache size                          155 MiB
Max cache size                       10 GiB



```

**Comment by TroyKomodo** [comment]
Freebsd test seems broken... Unrelated to this PR however.

**Comment by avikivity** [comment]
Does this work for distributed compilation as well? We need to detect the input modules the translation unit consumes and ship them to the build server, no?

**Comment by TroyKomodo** [comment]
Sccache isn't a distributed compiler. It's a cache with a pluggable distributed storage solution. This doesn't replace tools like bazel or buck2 when it comes to remote execution of the compiler.

**Comment by avikivity** [comment]
> Sccache isn't a distributed compiler. It's a cache with a pluggable distributed storage solution. This doesn't replace tools like bazel or buck2 when it comes to remote execution of the compiler.

It does advertise distributed compilation: https://github.com/mozilla/sccache/blob/main/docs/Distributed.md#distributed-sccache

**Comment by TroyKomodo** [comment]
> > Sccache isn't a distributed compiler. It's a cache with a pluggable distributed storage solution. This doesn't replace tools like bazel or buck2 when it comes to remote execution of the compiler.
> 
> It does advertise distributed compilation: https://github.com/mozilla/sccache/blob/main/docs/Distributed.md#distributed-sccache

Alright, well today i learnt. I have never used that feature before, I am not sure how it works in relation to this PR either. I don't know if it works implicitly or if I need to add more then telling it about the files to be aware of during completion. Maybe @mathstuf  knows more, likely will get a response in the next week or new year.

**Comment by avikivity** [comment]
I'm sure @mathstuf considers this his Christmas present and would like to play with it soonish

**Comment by mathstuf** [comment]
For distributed builds, `sccache` will need to rewrite `-fmodule-file=` arguments to:

- provide the content on the remote machine
- potentially rewrite the path on the remote (i.e., it may be `path/to/foo.bmi` locally, but can be rewritten to be `foo.bmi`)
- ship any `-fmodule-output=` contents back from the machine as well

MSVC is very similar to `clang` here and "just" needs argument rewrites (including in response files).

For GCC, the module mapper file will need to be rewritten on the remote. Any non-static file is going to have to be non-cacheable (pipes, processes, etc.). The `-fmodule-mapper=` file will also need shipped across and rewritten to answer module locations for where things are on the remote machine.

If paths are not preserved, `-MF` and `-showIncludes` dependency information will need to be rewritten back on the main host.

**Comment by mathstuf** [comment]
> I'm sure @mathstuf considers this his Christmas present and would like to play with it soonish

Alas, my *use* of modules is not likely to change, so this doesn't really affect me right now (finally migrated to C++17 on the main projects I work on; CMake's code itself still has C++11 expectations). My interest in getting modules usable by the community is definitely elated though :) .

**Comment by TroyKomodo** [comment]
> For distributed builds, `sccache` will need to rewrite `-fmodule-file=` arguments to:
> 
> * provide the content on the remote machine
> * potentially rewrite the path on the remote (i.e., it may be `path/to/foo.bmi` locally, but can be rewritten to be `foo.bmi`)
> * ship any `-fmodule-output=` contents back from the machine as well
> 
> MSVC is very similar to `clang` here and "just" needs argument rewrites (including in response files).
> 
> For GCC, the module mapper file will need to be rewritten on the remote. Any non-static file is going to have to be non-cacheable (pipes, processes, etc.). The `-fmodule-mapper=` file will also need shipped across and rewritten to answer module locations for where things are on the remote machine.
> 
> If paths are not preserved, `-MF` and `-showIncludes` dependency information will need to be rewritten back on the main host.

So are there any changes needed for this PR since this is specifically for clang?

**Comment by mathstuf** [comment]
The BMI inputs need pushed to the remote and the additional output needs pulled back. I don't know if the infrastructure does that already, but it should be testable by running a container as your remote compiler.

**Comment by sylvestre** [comment]
sorry but it needs to be rebased

**Comment by TroyKomodo** [comment]
> The BMI inputs need pushed to the remote and the additional output needs pulled back. I don't know if the infrastructure does that already, but it should be testable by running a container as your remot.e compiler.

I will figure this out this week, I was traveling over the christmas break so I havent had time to look at this PR yet.

If you could point me to where the code for the distributed cc lives so I can see how it works that would be great!

**Comment by mathstuf** [comment]
> If you could point me to where the code for the distributed cc lives so I can see how it works that would be great!

Look at `src/dist/mod.rs`. `BuildResult` would need built with the outputs. Inputs seem to be built into a `tar` file shipped via `InputsReader`. Chasing this down, it looks like `src/compiler/c.rs`'s `CInputsPackager` needs to learn to ship module files and munge module mapper arguments/files as necessary.

**Comment by avikivity** [comment]
Isn't this needed both for caching and for distributed compilation?

The inputs are needed for caching to check timestamps/sizes/hashes and for distribution to ship over the files. Note hashing the preprocessed output is insufficient.

The outputs are needed for caching to stash in the cache and for distribution so ship back.

For distribution, we might need to massage the command line, adding -fmodule-file for each input and output module to redirect them to out place in the filesystem.

**Comment by AJIOB** [comment]
> Isn't this needed both for caching and for distributed compilation?
> 
> The inputs are needed for caching to check timestamps/sizes/hashes and for distribution to ship over the files. Note hashing the preprocessed output is insufficient.
> 
> The outputs are needed for caching to stash in the cache and for distribution so ship back.
> 
> For distribution, we might need to massage the command line, adding -fmodule-file for each input and output module to redirect them to out place in the filesystem.

IMO, we can think about distributed compiling support in additional PR

**Comment by mathstuf** [comment]
Note that an initial investigation to at least drop "unsupported" errors and/or TODO comments in places would be useful for further work. It could also help avoid confusion by anyone trying modules and distributed builds in the interim.

**Comment by TroyKomodo** [comment]
> Note that an initial investigation to at least drop "unsupported" errors and/or TODO comments in places would be useful for further work. It could also help avoid confusion by anyone trying modules and distributed builds in the interim.

I am still traveling so I haven't had time to try out the distributed compiler. I wish there were better tests than to setup a docker container and try run it. I wasn't even aware the distributed compiler was a thing until someone pointed it out in this PRs comments. Since all the unit tests passed... If I don't do the full impl, I will at minimum add unsupported errors for modules when using distributed compiler mode. 

Sorry I haven't had time yet I should be fully settled down by Wednesday.

**Comment by mathstuf** [comment]
There's no rush on my account at least; take your time.

**Comment by AJIOB** [comment]
Hi @TroyKomodo,

Do you have any updates?

Looks like we have conflicts.

**Comment by TroyKomodo** [comment]
Okay! So i finally have gotten the time to look through this PR again. I think, this automatically works with dist mode since we add the PCMs to the `extra_hash_files` which are sent to the dist server automatically? 

Could someone please provide me with a way to test this or someone test this for me, using the integration test in the PR.

Integration tests fail because this branch is from a fork.

File: src/compiler/gcc.rs (hunk 2 above)
Comment (sylvestre) [reply src/compiler/gcc.rs]: i still want this to be a new function, sorry

**Comment by sylvestre** [comment]
> Integration tests fail because this branch is from a fork.

why do you think that ?

File: src/compiler/msvc.rs [hunk 5]
```diff
@@ -467,12 +475,14 @@ msvc_args!(static ARGS: [ArgInfo<ArgData>; _] = [
     msvc_flag!("openmp:experimental", PassThrough),
     msvc_flag!("permissive", PassThrough),
     msvc_flag!("permissive-", PassThrough),
+    msvc_take_arg!("reference", OsString, Separated, TooHard),
```
Comment (mathstuf) [inline src/compiler/msvc.rs:479]: The MSVC flags are very similar to Clang's. `-interface` and `-internalPartition` just need hashed like any other.

Can issues be opened and referenced from the comments for GCC and MSVC support?

**Comment by TroyKomodo** [comment]
> > Integration tests fail because this branch is from a fork.
> 
> why do you think that ?

Initially it spoke about missing an auth token when uploading. I think that was fixed in some other PR, after a rebase i think you (or me) resolved a merge incorrectly and it included additional ci jobs which were removed/changed which is why CI was failing before my last commit.

**Comment by avikivity** [comment]
Thanks a lot for implementing this feature.
