### PR TITLE
remove output files after preprocessing failures

### LINKED ISSUE #517: sccache should remove the object file when the preprocessor fails
See https://bugzilla.mozilla.org/show_bug.cgi?id=1540877#c13

### PR DESCRIPTION
**Pull request by froydnj**
Fixes #517.

### CODE REVIEW

**Comment by froydnj** [comment]
It's not totally clear to me whether to remove everything, or just the output file, but removing everything is likely the safest course.

File: src/compiler/c.rs [hunk 1]
```diff
@@ -245,8 +245,26 @@ impl<T, I> CompilerHasher<T> for CCompilerHasher<I>
...
         let out_pretty = parsed_args.output_pretty().into_owned();
         let extra_hashes = hash_all(&parsed_args.extra_hash_files, &pool.clone());
+        let outputs = parsed_args.outputs.clone();
+        let args_cwd = cwd.clone();
 
         Box::new(result.or_else(move |err| {
+            // Errors remove all traces of potential output.
+            debug!("removing files {:?}", &outputs);
+
+            let v: std::result::Result<Vec<()>, std::io::Error> = outputs.values().map(|f| {
```
Comment (chmanchester) [inline src/compiler/c.rs]: The Vec of empty values we don't consult seems unnecessary, maybe this can be something like a `fold`?

File: src/compiler/c.rs [hunk 2]
```diff
@@ -245,8 +245,26 @@ impl<T, I> CompilerHasher<T> for CCompilerHasher<I>
...
+                let mut path = (&args_cwd).clone();
+                path.push(&f);
```
[the remark this answers is not in the document]
Comment (froydnj) [reply src/compiler/c.rs]: The documentation for `PathBuf::Push` says that if the argument provided is an absolute path, it replaces anything in the `PathBuf`.  So I think we are OK here.

File: src/compiler/c.rs (hunk 1 above)
Comment (froydnj) [reply src/compiler/c.rs]: The motivation was not worrying too much about the performance of error cases, but I like the `fold` idea better.  I'll use that, thanks!
