### PR TITLE
Fix remaining freebsd-ci problems

### LINKED ISSUE #1536: freebsd tests failed during Deinstall pot (potpool/pot)
FreeBSD tests still failing: https://github.com/mozilla/sccache/actions/runs/3872236759/jobs/6600856845

```shell
  ===>  Deinstall pot (potpool/pot)
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-cc7b8d3c-d33b-4d5b-a423-6fea3c6616ff/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-cc7b8d3c-d33b-4d5b-a423-6fea3c6616ff': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-81f44083-dca0-4653-8870-c0c12db583ef/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-81f44083-dca0-4653-8870-c0c12db583ef': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-701444f1-2007-4546-b403-19069594e48c/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-701444f1-2007-4546-b403-19069594e48c': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-cc7b8d3c-d33b-4d5b-a423-6fea3c6616ff/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-81f44083-dca0-4653-8870-c0c12db583ef/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-701444f1-2007-4546-b403-19069594e48c/m': pool or dataset is busy
  cannot destroy snapshot potpool/pot/jails/sccache-image-554cc6e001bb5d08d79d8efc2c1d5955739bdc918ed49b8bc04a0a87119b554b/m@1673256029: snapshot is cloned
  cannot destroy snapshot potpool/pot/jails/sccache-template/m@1673255921: snapshot is cloned
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-template': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-cc7b8d3c-d33b-4d5b-a423-6fea3c6616ff/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-81f44083-dca0-4653-8870-c0c12db583ef/m': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-builder-701444f1-2007-4546-b403-19069594e48c/m': pool or dataset is busy
  cannot destroy snapshot potpool/pot/jails/sccache-image-554cc6e001bb5d08d79d8efc2c1d5955739bdc918ed49b8bc04a0a87119b554b/m@1673256029: snapshot is cloned
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails/sccache-image-554cc6e001bb5d08d79d8efc2c1d5955739bdc918ed49b8bc04a0a87119b554b': pool or dataset is busy
  cannot unmount '/tmp/sccache_freebsd.QYiN9iu/pot/jails': pool or dataset is busy
  cannot destroy 'potpool/pot': dataset already exists
  sed: /etc/pf.conf: No such file or directory
  sed: /etc/pf.conf: No such file or directory
  zfs datasets have been removed
  pf configuration file should be clean (please check /etc/pf.conf)
  check your rc.conf for potential leftovers variable like:
    syslogd_flags
    pot_enable
  Please, consider to write a feedback email to pizzamig at FreeBSD dot org
  It gives us the opportunity to learn and improve
  exec shell: bash run.sh showDebugInfo
```

### PR DESCRIPTION
**Pull request by grembo**
Fixes #1536

### CODE REVIEW

File: scripts/freebsd-ci-test.sh [hunk 1]
```diff
@@ -290,6 +292,7 @@ test_sccache_dist_02()
 
 cleanup()
 {
+	trap - EXIT INT HUP
```
Comment (sylvestre) [inline scripts/freebsd-ci-test.sh:295]: could you please add a comment here?

Comment (grembo) [reply scripts/freebsd-ci-test.sh]: @sylvestre I'll clean it up a bit so it's clear how it works (please ignore the intermediate commit)

Comment (grembo) [reply scripts/freebsd-ci-test.sh]: @sylvestre Code should be more obvious now.

Let's wait for CI builds to finish.
